<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Gourav" failures="0" tests="9" name="common_files.TestSec50UatSf" time="74.188" errors="1" timestamp="2024-05-10T11:05:19 IST" skipped="0">
  <testcase classname="common_files.TestSec50UatSf" name="OpenWestminsterBoUrl" time="11.664"/>
  <testcase classname="common_files.TestSec50UatSf" name="confirmInformation" time="1.382">
    <error message="expected:&lt;...tru...&gt; but was:&lt;...fals...&gt;" type="junit.framework.ComparisonFailure">
      <![CDATA[junit.framework.ComparisonFailure: expected:<...tru...> but was:<...fals...>
at junit.framework.Assert.assertEquals(Assert.java:81)
at junit.framework.Assert.assertEquals(Assert.java:87)
at common_files.TestSec50UatSf.confirmInformation(TestSec50UatSf.java:51)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- confirmInformation -->
  <testcase classname="common_files.TestSec50UatSf" name="fillingApplicationDates" time="1.500"/>
  <testcase classname="common_files.TestSec50UatSf" name="fillingSiteDetails" time="4.040"/>
  <testcase classname="common_files.TestSec50UatSf" name="fillAboutTheWorkSection" time="1.354"/>
  <testcase classname="common_files.TestSec50UatSf" name="fillSupervisorDetails" time="18.399"/>
  <testcase classname="common_files.TestSec50UatSf" name="fillOperatorDetails" time="18.356"/>
  <testcase classname="common_files.TestSec50UatSf" name="addDeclarations" time="8.376"/>
  <testcase classname="common_files.TestSec50UatSf" name="payFees" time="9.117"/>
</testsuite> <!-- common_files.TestSec50UatSf -->
